### PR TITLE
read task info from list format instead of CSV

### LINKED ISSUE #545: Bug: can't read registered tasks on windows
If scheduled task has double quotes in command arguments, resticprofile can't parse it (unschedule and status commands fail). This may happen if path to config needs to be escaped, for example:

> resticprofile -c "C;\folder with spaces\profiles.yaml" schedule --all

This task is schduled:
Command: resticprofile.exe
Arguments: --no-ansi --config "C;\folder with spaces\profiles.yaml" run-schedule backup@default

And now we are unable to unschedule it:
>resticprofile -c "C:\folder with spaces\profiles.yaml" unschedule --all
>2025/07/31 00:06:50 loading task "\\resticprofile backup\\default backup": %!w(*csv.ParseError=&{2 2 235 0x21c7670})
>2025/07/31 00:06:50 no scheduled jobs found

Problem is `getCSV` can't parse output of schtasks cuz output contains unescaped double quotes:

> schtasks /query /fo csv /v /tn "\resticprofile backup\default backup"

```csv
"HostName","TaskName","Next Run Time","Status","Logon Mode","Last Run Time","Last Result","Author","Task To Run","Start In","Comment","Scheduled Task State","Idle Time","Power Management","Run As User","Delete Task If Not Rescheduled","Stop Task If Runs X Hours and X Mins","Schedule","Schedule Type","Start Time","Start Date","End Date","Days","Months","Repeat: Every","Repeat: Until: Time","Repeat: Until: Duration","Repeat: Stop If Still Running"
"HOSTNAME","\resticprofile backup\default backup","2025-08-01 00:00:00","Ready","Interactive only","1999-11-30 00:00:00","267011","resticprofile","resticprofile.exe --no-ansi --config "C:\folder with spaces\profiles.yaml" run-schedule backup@default","C:\Windows\system32","resticprofile backup for profile default in C:\folder with spaces\profiles.yaml","Enabled","Disabled","Stop On Battery Mode, No Start On Batteries","HOSTNAME\zumm","Disabled","Disabled","Scheduling data is not available in this format.","Daily ","N/A","N/A","N/A","Every 1 day(s)","N/A","Disabled","Disabled","Disabled","Disabled"
```

A possible solution is to use the /xml flag to get the output in XML format. However, this flag cannot be used together with /v.

### PR DESCRIPTION
**Pull request by creativeprojects**
## Refactor Windows task scheduler to use list format instead of CSV

This PR refactors the Windows task scheduler implementation to read task information from the schtasks list format instead of CSV format.

**Key Changes:**
- **New parser**: Added `getTaskInfoFromList()` function to parse key-value pairs from list format output
- **Command change**: Modified schtasks command to use `/fo list` instead of `/fo csv`
- **Data structure**: Changed from `[][]string` (CSV rows) to `[]map[string]string` (key-value records)
- **Improved parsing**: Better handling of different separator formats (`:  ` and `: `)
- **Enhanced testing**: Added comprehensive tests for the new list format parser

**Benefits:**
- More robust parsing of task information
- Better handling of complex field values that may contain quotes
- Cleaner data structure for accessing task properties by name
- Improved error handling for malformed data

The change maintains backward compatibility while providing a more reliable way to extract Windows scheduled task information.

Fixes #545

### CODE REVIEW

File: schtasks/list_test.go [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+Folder: \resticprofile backup
+HostName:                             WIN-5NMJF0VS8OR
+TaskName:                             \resticprofile backup\self backup
+Next Run Time:                        04/08/2025 21:15:00
+Status:                               Ready
+Logon Mode:                           Interactive only
+Last Run Time:                        04/08/2025 21:00:01
+Last Result:                          1
+Author:                               resticprofile
+Task To Run:                          G:\go\src\github.com\creativeprojects\resticprofile\resticprofile.exe --no-ansi --config "examples\othere windows.yaml" run-schedule backup@self
```
Comment (zumm) [inline schtasks/list_test.go]: Seems like a typo here (and below): "othere"

Comment (creativeprojects) [reply schtasks/list_test.go]: It took me a while to find out it that was `golangci-lint run --fix` who did that: it was ignoring the `o` from the word because of the backslash in front, then fixing the word `thr` into `there` 🤷🏻‍♂️

**Comment by creativeprojects** [comment]
PR is ready to merge,
@zumm does it work for you?

**Comment by zumm** [comment]
I have tested it with spaces in path to config file and it seems like unschedule/status commands work fine.
